import '../styles/globals.css'
import Head from 'next/head'
import type { AppProps } from 'next/app'
import Nav from '../components/Nav/Nav'
import { JuegoProvider } from '../store/context/juego'
import { JugadoresProvider } from '../store/context/jugadoresContext'


function MyApp({ Component, pageProps }: AppProps) {

  return <>
    <JuegoProvider>
      <JugadoresProvider>
        <Head>
          <title>Amigos de mierda</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/icono.png" />
        </Head>
        <Nav />
        <Component {...pageProps} />
      </JugadoresProvider>
    </JuegoProvider>
  </>
}

export default MyApp
