import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useContext } from 'react'
import { JuegoContext } from '../store/context/juego'
import styles from '../styles/Home.module.css'


const Home: NextPage = () => {

  const { traerCarta, loading, mazo } = useContext(JuegoContext)

  const pepito = () => {


    traerCarta()
  }



  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.wrapbutton}>
          <button className={styles.partida}><Link href='/configuracion'>Crear partida</Link></button>
          <button className={styles.reglas}><Link href='/reglas'>Reglas</Link></button>


        </div>
      </main>


    </div>
  )
}

export default Home
